"use client";

import { upload } from "@vercel/blob/client";
import { useEffect, useState } from "react";

type Prompt = {
  id: string;
  title: string;
  constraint?: string | null;
  twist?: string | null;
};

type Photo = { imagePath: string; caption?: string | null; mood?: string | null } | null;

export default function TodayPage() {
  const [loading, setLoading] = useState(true);
  const [todayKey, setTodayKey] = useState("");
  const [prompt, setPrompt] = useState<Prompt | null>(null);
  const [photo, setPhoto] = useState<Photo>(null);

  const [caption, setCaption] = useState("");
  const [mood, setMood] = useState<string>("");
  const [tip, setTip] = useState<string>("");

  async function load() {
    setLoading(true);
    const res = await fetch("/api/today", { cache: "no-store" });
    const data = await res.json();
    setTodayKey(data.todayKey);
    setPrompt(data.prompt);
    setPhoto(data.photo);
    setCaption(data.photo?.caption ?? "");
    setMood(data.photo?.mood ?? "");
    setLoading(false);
  }

  useEffect(() => {
    void load();
  }, []);

  async function onUpload(file: File) {
    try {
      // 1) Upload file to Blob (client token generated by /api/blob)
      const blob = await upload(file.name, file, {
        access: "public",
        handleUploadUrl: "/api/blob",
      });

      // 2) Save blob URL + metadata to DB
      const res = await fetch("/api/photo/upload", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ imagePath: blob.url, caption, mood }),
      });

      if (!res.ok) {
        const msg = await res.text();
        alert(`upload failed: ${res.status} ${msg}`);
        return;
      }

      await load();
    } catch (e: any) {
      alert(`blob upload failed: ${e?.message ?? String(e)}`);
    }
  }

  async function getStuckTip() {
    const res = await fetch("/api/stuck", { cache: "no-store" });
    const data = await res.json();
    setTip(data.tip);
  }

  if (loading) return <main className="container">loading…</main>;

  return (
    <main className="container">
      <nav className="nav">
        <a href="/">today</a>
        <a href="/archive">archive</a>
        <a href="/progress">progress</a>
      </nav>

      <div className="h1">Daily Frame</div>
      <p className="meta">today: {todayKey}</p>

      {prompt && (
        <section className="card">
          <div className="label">today’s prompt</div>
          <div className="prompt">{prompt.title}</div>

          {prompt.constraint && (
            <>
              <div className="label">constraint</div>
              <p className="value">{prompt.constraint}</p>
            </>
          )}

          {prompt.twist && (
            <>
              <div className="label">optional twist</div>
              <p className="value">{prompt.twist}</p>
            </>
          )}

          <div style={{ marginTop: 12 }}>
            <button className="secondary" onClick={getStuckTip}>
              i’m stuck →
            </button>
            {tip && (
              <p className="small" style={{ marginTop: 10 }}>
                <em>{tip}</em>
              </p>
            )}
          </div>
        </section>
      )}

      <section style={{ marginTop: 18 }}>
        <div className="label">today’s photo</div>

        {photo?.imagePath ? (
          <div style={{ marginTop: 10 }}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img className="photo" src={photo.imagePath} alt="today" />
            <p className="small" style={{ marginTop: 10 }}>
              you can replace this until midnight
            </p>
          </div>
        ) : (
          <p className="small" style={{ marginTop: 10 }}>
            no photo yet. upload one to lock in your day.
          </p>
        )}

        <div className="grid" style={{ marginTop: 12 }}>
          <label className="label">
            caption (optional)
            <input value={caption} onChange={(e) => setCaption(e.target.value)} />
          </label>

          <label className="label">
            mood (optional)
            <select value={mood} onChange={(e) => setMood(e.target.value)}>
              <option value="">—</option>
              <option value="Calm">calm</option>
              <option value="Moody">moody</option>
              <option value="Joyful">joyful</option>
              <option value="Curious">curious</option>
              <option value="Gritty">gritty</option>
            </select>
          </label>

          <label className="label">
            upload image
            <input
              type="file"
              accept="image/*"
              onChange={(e) => {
                const f = e.target.files?.[0];
                if (f) void onUpload(f);
              }}
            />
          </label>
        </div>
      </section>

      <style jsx global>{`
        :root {
          color-scheme: dark;
        }
        html,
        body {
          background: #000;
          color: #fff;
          font-family: "Courier New", Courier, monospace;
        }
        a {
          color: #fff;
          text-decoration: none;
          opacity: 0.9;
        }
        a:hover {
          opacity: 1;
          text-decoration: underline;
        }
        .container {
          max-width: 760px;
          margin: 0 auto;
          padding: 28px 16px 64px;
        }
        .nav {
          display: flex;
          gap: 16px;
          margin-bottom: 22px;
        }
        .h1 {
          font-size: 34px;
          letter-spacing: 0.5px;
          margin-bottom: 6px;
        }
        .meta {
          opacity: 0.75;
          margin-bottom: 18px;
        }
        .card {
          border: 1px solid rgba(255, 255, 255, 0.2);
          padding: 14px 14px 16px;
        }
        .label {
          display: block;
          font-size: 12px;
          letter-spacing: 1.2px;
          text-transform: uppercase;
          opacity: 0.7;
          margin-bottom: 6px;
        }
        .prompt {
          font-size: 22px;
          margin-bottom: 12px;
        }
        .value {
          margin: 0 0 10px 0;
          opacity: 0.9;
        }
        .small {
          font-size: 13px;
          opacity: 0.8;
          margin: 0;
        }
        .grid {
          display: grid;
          grid-template-columns: 1fr 1fr 1fr;
          gap: 12px;
          align-items: end;
        }
        input,
        select {
          width: 100%;
          background: #000;
          color: #fff;
          border: 1px solid rgba(255, 255, 255, 0.25);
          padding: 10px 10px;
          font-family: inherit;
          font-size: 14px;
        }
        button {
          background: #000;
          color: #fff;
          border: 1px solid rgba(255, 255, 255, 0.35);
          padding: 10px 12px;
          font-family: inherit;
          cursor: pointer;
        }
        button.secondary {
          opacity: 0.95;
        }
        .photo {
          width: 100%;
          height: auto;
          border: 1px solid rgba(255, 255, 255, 0.25);
        }
        @media (max-width: 760px) {
          .grid {
            grid-template-columns: 1fr;
          }
        }
      `}</style>
    </main>
  );
}